language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"

matrix:
    allow_failures:
        - python: "3.2"
        - python: "pypy"

install:
  - python setup.py install
  - pip install Twisted --use-mirrors

script: bash .run.travis.run.sh
